from flask import Flask, render_template, request, jsonify, send_file, session
from pathlib import Path
import os
import json
import subprocess
import sys
import threading
from datetime import datetime, timedelta
import shutil
import secrets

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 2 * 1024 * 1024 * 1024  # 2GB max file upload
app.config['UPLOAD_FOLDER'] = 'uploads'
app.config['TEMP_OUTPUT_FOLDER'] = 'temp_outputs'
app.secret_key = secrets.token_hex(32)

# Create folders if they don't exist
Path(app.config['UPLOAD_FOLDER']).mkdir(exist_ok=True)
Path(app.config['TEMP_OUTPUT_FOLDER']).mkdir(exist_ok=True)

# Store processing status and session temp folders
processing_status = {}
session_temp_folders = {}

@app.route('/')
def index():
    # Create a unique session folder for this user
    if 'session_id' not in session:
        session_id = secrets.token_hex(16)
        session['session_id'] = session_id
        temp_folder = Path(app.config['TEMP_OUTPUT_FOLDER']) / session_id
        temp_folder.mkdir(exist_ok=True)
        session_temp_folders[session_id] = temp_folder
    return render_template('index.html')

@app.route('/api/available-videos', methods=['GET'])
def get_available_videos():
    """Get list of available video files"""
    videos = []
    
    # Check uploaded videos
    if Path(app.config['UPLOAD_FOLDER']).exists():
        for video in Path(app.config['UPLOAD_FOLDER']).glob('*'):
            if video.is_file() and video.suffix.lower() in ['.mp4', '.avi', '.mov', '.mkv']:
                videos.append({
                    'name': video.name,
                    'path': str(video),
                    'size': video.stat().st_size,
                    'source': 'uploaded'
                })
    
    # Check root directory for existing videos
    for video in Path('.').glob('*.mp4'):
        if video.is_file():
            videos.append({
                'name': video.name,
                'path': str(video),
                'size': video.stat().st_size,
                'source': 'local'
            })
    
    return jsonify(videos)

@app.route('/api/process-video', methods=['POST'])
def process_video():
    """Process selected video file"""
    data = request.json
    video_path = data.get('video_path')
    
    if not video_path or not Path(video_path).exists():
        return jsonify({'error': 'Video file not found'}), 400
    
    # Get session temp folder
    session_id = session.get('session_id')
    if not session_id:
        return jsonify({'error': 'Session error'}), 400
    
    # Generate unique job ID
    job_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    processing_status[job_id] = {
        'status': 'processing',
        'video': video_path,
        'progress': 0,
        'message': 'Processing video...',
        'session_id': session_id
    }
    
    # Process in background thread
    thread = threading.Thread(
        target=process_vehicle_detection,
        args=(job_id, video_path, session_id)
    )
    thread.daemon = True
    thread.start()
    
    return jsonify({'job_id': job_id, 'status': 'started'})

@app.route('/api/process-status/<job_id>', methods=['GET'])
def get_process_status(job_id):
    """Get processing status"""
    if job_id not in processing_status:
        return jsonify({'error': 'Job not found'}), 404
    
    return jsonify(processing_status[job_id])

@app.route('/api/upload-video', methods=['POST'])
def upload_video():
    """Handle video file upload"""
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'}), 400
    
    file = request.files['file']
    
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400
    
    if not file.filename.lower().endswith(('.mp4', '.avi', '.mov', '.mkv')):
        return jsonify({'error': 'Invalid video format'}), 400
    
    filename = Path(file.filename).name
    filepath = Path(app.config['UPLOAD_FOLDER']) / filename
    file.save(str(filepath))
    
    return jsonify({
        'success': True,
        'filename': filename,
        'path': str(filepath)
    })

@app.route('/api/output-files/<job_id>', methods=['GET'])
def get_output_files(job_id):
    """Get output files generated by processing"""
    if job_id not in processing_status:
        return jsonify({'error': 'Job not found'}), 404
    
    # Get stored output files from processing status
    saved_files = processing_status[job_id].get('output_files', [])
    outputs = []
    
    for file_info in saved_files:
        if Path(file_info['path']).exists():
            outputs.append({
                'name': file_info['name'],
                'path': f'/api/download/{file_info["name"]}',
                'type': file_info['type']
            })
    
    return jsonify(outputs)

@app.route('/api/download/<filename>', methods=['GET'])
def download_file(filename):
    """Download processed file from session temp folder"""
    session_id = session.get('session_id')
    if not session_id:
        return jsonify({'error': 'Session error'}), 400
    
    temp_folder = session_temp_folders.get(session_id)
    if not temp_folder:
        temp_folder = Path(app.config['TEMP_OUTPUT_FOLDER']) / session_id
    
    file_path = temp_folder / filename
    
    if not file_path.exists() or not file_path.is_file():
        return jsonify({'error': 'File not found'}), 404
    
    return send_file(str(file_path), as_attachment=True)

@app.route('/api/cleanup-session', methods=['POST'])
def cleanup_session():
    """Clean up session temp folder when user leaves"""
    session_id = session.get('session_id')
    if session_id and session_id in session_temp_folders:
        temp_folder = session_temp_folders[session_id]
        try:
            if temp_folder.exists():
                shutil.rmtree(str(temp_folder))
            del session_temp_folders[session_id]
        except Exception as e:
            print(f"Error cleaning up session {session_id}: {e}")
    
    return jsonify({'status': 'cleaned'})

def process_vehicle_detection(job_id, video_path, session_id):
    """Run vehicle detection on video"""
    try:
        processing_status[job_id]['message'] = 'Modifying vehicle detection script...'
        processing_status[job_id]['output_files'] = []
        
        # Get session temp folder
        temp_folder = session_temp_folders.get(session_id)
        if not temp_folder:
            temp_folder = Path(app.config['TEMP_OUTPUT_FOLDER']) / session_id
            temp_folder.mkdir(exist_ok=True)
            session_temp_folders[session_id] = temp_folder
        
        # Read original script
        with open('vehicle_detection.py', 'r') as f:
            script = f.read()
        
        # Replace video source and outputs folder with temp folder
        # Convert paths to use forward slashes to avoid escape sequence issues
        video_path_safe = video_path.replace('\\', '/')
        temp_folder_safe = str(temp_folder).replace('\\', '/')
        
        modified_script = script.replace(
            'cap = cv2.VideoCapture("road.mp4")',
            f'cap = cv2.VideoCapture("{video_path_safe}")'
        )
        modified_script = modified_script.replace(
            'outputs_dir = Path("outputs")',
            f'outputs_dir = Path("{temp_folder_safe}")'
        )
        
        # Write to temp script
        temp_script = f'temp_detect_{job_id}.py'
        with open(temp_script, 'w') as f:
            f.write(modified_script)
        
        processing_status[job_id]['message'] = 'Processing video with vehicle detection...'
        processing_status[job_id]['progress'] = 25
        
        # Run the detection
        result = subprocess.run(
            [sys.executable, temp_script],
            capture_output=True,
            text=True,
            timeout=3600
        )
        
        if result.returncode != 0:
            processing_status[job_id]['status'] = 'error'
            processing_status[job_id]['message'] = f"Error: {result.stderr}"
        else:
            # Parse output to find saved files
            output_text = result.stdout + result.stderr
            saved_files = []
            
            for line in output_text.split('\n'):
                if 'Saved output video:' in line:
                    # Extract file path from "Saved output video: path/to/file.mp4"
                    file_path = line.split('Saved output video:')[1].strip()
                    if Path(file_path).exists():
                        saved_files.append({
                            'name': Path(file_path).name,
                            'path': file_path,
                            'type': 'video'
                        })
                elif 'Saved detection log:' in line:
                    # Extract file path from "Saved detection log: path/to/file.csv"
                    file_path = line.split('Saved detection log:')[1].strip()
                    if Path(file_path).exists():
                        saved_files.append({
                            'name': Path(file_path).name,
                            'path': file_path,
                            'type': 'csv'
                        })
            
            processing_status[job_id]['output_files'] = saved_files
            
            # Create summary message
            if saved_files:
                file_list = '\n'.join([f"  • {f['name']} ({f['type'].upper()})" for f in saved_files])
                processing_status[job_id]['message'] = f"✓ Processing completed!\n\nGenerated files:\n{file_list}"
            else:
                processing_status[job_id]['message'] = 'Processing completed! (Output files not found in output directory)'
            
            processing_status[job_id]['status'] = 'completed'
            processing_status[job_id]['progress'] = 100
        
        # Clean up temp script
        Path(temp_script).unlink(missing_ok=True)
        
    except Exception as e:
        processing_status[job_id]['status'] = 'error'
        processing_status[job_id]['message'] = f"Exception: {str(e)}"

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5001)
